version: '3.7'
services:
  fastapi:
    build:
      context: .
      dockerfile: fastpi.dockerfile
    container_name: fastapi
    hostname: dynamodb
    volumes:
      - $HOME/.aws/credentials:/root/.aws/credentials:ro
    ports:
      - 80:80
  dynamodb:
    build:
      context: .
      dockerfile: dynamodb.dockerfile
    container_name: my-dynamodb
    hostname: dynamodb
    restart: always
    volumes:
      - ./my-dynamodb-data:/home/dynamodblocal/data
      - $HOME/.aws/credentials:/home/app/.aws/credentials:ro
    ports:
      - 8000:8000
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data/"
