version: '3.7'
services:
  service:
    image: service:latest
    container_name: service
    ports:
      - 80:80
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
        window: 120s
