version: '3.7'
services:
  service:
    image: service:latest
    container_name:
    hostname: dynamodb
    volumes:
      - $HOME/.aws/credentials:/root/.aws/credentials:ro
    ports:
      - 80:80
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s

