pipeline {
    agent any
    stages {
        stage('Example') {
            steps {
                script {
                    checkout([$class: 'GitSCM', branches: [[name: '${service_revision}']], extensions: [], userRemoteConfigs: [[credentialsId: 'repository', url: 'git@github.com:AhmadG-coder/Payoneer-exercise.git']]])
                }
            }
        }
    }
}